import { mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { claudeCodeSkillsDir } from "../paths.js";

export const proposeNewSkillInput = z.object({
  task_description: z
    .string()
    .min(10)
    .describe(
      "What the user is trying to do. The more concrete, the better the resulting SKILL.md draft."
    ),
  slug: z
    .string()
    .regex(/^[a-z0-9][a-z0-9-]*[a-z0-9]$/)
    .optional()
    .describe(
      "Slug for the new skill directory. If omitted, derived from task_description."
    ),
  triggers: z
    .array(z.string())
    .optional()
    .describe("Keywords / phrases that should activate this skill in future sessions."),
  draft_body: z
    .string()
    .optional()
    .describe(
      "Optional SKILL.md body. If omitted, a stub is written and the assistant should ask the user follow-up questions to fill it out."
    ),
});

export const proposeNewSkillDescription = `Create a draft SKILL.md when no catalog entry matches the user's need.

When to call:
  - find_skill returned no useful matches.
  - The user described a workflow novel enough that it deserves its own skill.

Behavior:
  - Writes a draft to ~/.claude/skills/<slug>/SKILL.md.
  - The draft is intentionally lightweight — Claude (you) is expected to iterate with the user, edit the file in place, and ultimately encourage them to PR it back to the community.

Suggested follow-up after calling:
  1. Tell the user where the file landed.
  2. Offer to refine triggers and instructions in a second pass.
  3. Mention they can contribute it to https://github.com/gyuch-an02/claude-omakase/tree/main/handpicked once it's stable.`;

export async function handle(args: z.infer<typeof proposeNewSkillInput>) {
  const slug = args.slug ?? slugify(args.task_description);
  const dir = join(claudeCodeSkillsDir(), slug);
  mkdirSync(dir, { recursive: true });

  const triggers = args.triggers && args.triggers.length > 0 ? args.triggers : derive_triggers(args.task_description);
  const body =
    args.draft_body ??
    defaultBody({ slug, taskDescription: args.task_description, triggers });

  const path = join(dir, "SKILL.md");
  await writeFile(path, body, "utf8");

  return {
    ok: true,
    slug,
    path,
    next_steps: [
      `Open ${path} and refine the instructions.`,
      "Test the skill by running a fresh Claude session.",
      "When happy, copy SKILL.md content into a PR under handpicked/ in the claude-omakase repo.",
    ],
  };
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
}

function derive_triggers(s: string): string[] {
  return [
    ...new Set(
      s
        .toLowerCase()
        .split(/[^a-z0-9가-힣]+/)
        .filter((w) => w.length > 3)
        .slice(0, 6)
    ),
  ];
}

function defaultBody(params: {
  slug: string;
  taskDescription: string;
  triggers: string[];
}): string {
  const { slug, taskDescription, triggers } = params;
  return `---
name: ${slug}
description: DRAFT — generated by Claude Omakase propose_new_skill. Refine before publishing.
triggers: [${triggers.map((t) => JSON.stringify(t)).join(", ")}]
---

# ${slug}

> Draft skill. Iterate with Claude in chat to make this concrete.

## What this skill does

${taskDescription}

## When to activate

Claude should use this skill when the user is doing any of:

${triggers.map((t) => `- "${t}"`).join("\n")}

## Steps

1. (TODO) Describe the first concrete action.
2. (TODO) Describe the next action.
3. (TODO) Describe success criteria so Claude knows when to stop.

## Examples

- (TODO) Add a real example dialogue.

---

_Generated ${new Date().toISOString()} by claude-omakase. Replace this TODO scaffold with concrete instructions before relying on it._
`;
}
